#! /bin/bash

numAleatorio=$(( RANDOM % 100 + 1 ))

echo "Se genero un numero entre 1 y 100, intenta adivinarlo!"


while true
do

read -p "Ingresa tu numero: " numAdivinar

  
  if (( numAdivinar < 1 || numAdivinar > 100 ))
  then 
    echo "El numero ingresado no es valido, intentelo nuevamente."
  elif (( numAdivinar < numAleatorio ))
  then
    echo "El numero que ingresaste es menor, intentalo de nuevo."
  elif (( numAdivinar > numAleatorio ))
  then
    echo "El numero que ingresaste es mayor, intentalo de nuevo."
  else
    echo "Adivinaste el numero, el cual era: $numAleatorio"
    break
  fi
done

