#! /bin/bash

numAleatorio=$(( RANDOM % 100 + 1 ))

echo "Se genero un numero entre 1 y 100, intenta adivinarlo!"

numAdivinar=0 

while true
do
  read -p "Ingresa tu numero: " numAdivinar

  if (( numAdivinar < numAleatorio ))
  then
    echo "El numero que ingresaste es menor, intentalo de nuevo."
  elif (( numAdivinar > numAleatorio ))
  then
    echo "El numero que ingresaste es mayor, intentalo de nuevo."
  else
    echo "Adivinaste el numero, el cual era: $numAleatorio"
    break
  fi
done
